### PR TITLE
feat: Relates to #402. Internationalisation. German Language Support

### PR DESCRIPTION
**Pull request by ltfschoen**
* [x] Merge latest from Internationalisation Base Support PR #452 (due to fix merge conflicts since https://github.com/paritytech/fether/pull/452/commits/88c9b18dd808b562002541c0ac0baec0ce377cf2)

* [x] Update de.json after convert all text in fether-electron i18n config file into i18n. See https://github.com/paritytech/fether/pull/452/commits/88c9b18dd808b562002541c0ac0baec0ce377cf2#diff-e71da345e8fcc8df02de6ee26e679513R43 due to dot point in #452. **Not required as discussed with Tbaut**

* [x] Update de.json after convert all text in fether-react i18n config file into i18n due to dot point in #452 **Not required as discussed with Tbaut**

* [x] Update de.json files with converson of all text in scripts/fetch-latest-parity.js into i18n due to dot point in #452 **Not required as discussed with Tbaut**

* [x] Remove `"downloading": "Downloading Parity Ethereum...",` from packages/fether-react/src/i18n/locales/de.json in German translation PR

* [x] Update packages/fether-react/src/i18n/locales/de.json to it's `validation.` instead of `validation.alert`, and replace all occurrences

* [x] Add to packages/fether-react/src/i18n/locales/de.json `validation.valid_tx`, and update occurrence after merge

* [x] Remove from packages/fether-react/src/i18n/locales/de.json the whole `validation.throw` section

* [x] Add the following to packages/fether-react/src/i18n/locales/de.json with German translation:
```
        "fetching_chain_id": "Fetching chain ID",
        "fetching_eth_balance": "Fetching Ether balance",
        "fetching_tx_count": "Fetching transaction count for nonce",
```

* [x] Add the following to packages/fether-react/src/i18n/locales/de.json with German translation:
```
  "releases": {
    "new_release_title": "New version available",
    "new_release_description": "{{release_name}} was released!"
  },
```

* [x] Remove from packages/fether-react/src/i18n/locales/de.json the whole `health.token_list` key/value section

* [x] Peer review of Fether menu by someone fluent in German (since I just used Google Translate). fether-electron/src/main/app/menu/i18n/locales/de.json. Review completed thanks to @Robbepop

* [x] Peer review of the Fether contents by someone fluent in German (since I just used Google Translate). fether-react/src/i18n/locales/de.json **Propose the merge and create an issue requesting "proper" translation of this file by an open-source German native language speaker.**

### CODE REVIEW

**Comment by Tbaut** [comment]
I removed the "goodfirstissue" as this is a label for issues. We should create some proper issues for that.

**Comment by ltfschoen** [comment]
@amaurymartiny @Tbaut i've merged latest from 'master' and from 'luke-402-i18n' branches and fixed merge conflicts, an

* Merge latest from master
* Addressed all bulletpoints in the summary of this PR https://github.com/paritytech/fether/pull/464#issue-261878436 (except for bullet point that relates to translation of the 2nd de.json file, as we require a native German language speaker). **Propose the merge and create an issue requesting "proper" translation of this file.**

To switch between languages, just right-click in the Fether window to open the Fether context menu, choose Preferences > Language > English or German.
Then the Fether window will refresh and show it in the other language.

**Comment by ltfschoen** [comment]
@amaurymartiny @Tbaut i've merged latest from 'master' and from 'luke-402-i18n' branches and fixed merge conflicts, an

* Merge latest from master
* Addressed all bulletpoints in the summary of this PR https://github.com/paritytech/fether/pull/464#issue-261878436 (except for bullet point that relates to translation of the 2nd de.json file, as we require a native German language speaker). **Propose the merge and create an issue requesting "proper" translation of this file.**

To switch between languages, just right-click in the Fether window to open the Fether context menu, choose Preferences > Language > English or German.
Then the Fether window will refresh and show it in the other language.

**Comment by ltfschoen** [comment]
i've created a Fether FAQ PR https://github.com/paritytech/wiki/pull/327 that explains:
* How to switch between languages that Fether supports?
* How to add support for a new language to Fether?

**Comment by Tbaut** [comment]
Sorry I've mistakenly  merged the `luke-402-i18n` to master before. Created https://github.com/paritytech/fether/pull/510/ to merge this one to master now.

**Comment by amaurymartiny** [comment]
Or you could change the base of this one in the top-right Edit button on Github

**Comment by Tbaut** [comment]
:) for some reason I thought only Luke could do that, thanks

**Pull request merged**
