### PR TITLE
Fix linux icon

### LINKED ISSUE #190: Fether doesn't have any logo/icon on linux
Installing though the latest tar.gz on GitHub as well as `yarn package`.
Same for the .deb (created by the above command):
image

### PR DESCRIPTION
**Pull request by amaurymartiny**
Fix #190.

The only difference I saw with Parity UI's config was the icon size on Linux, so I changed it to 512x512. Long shot.

@Tbaut can you try `yarn package` on this branch?

### CODE REVIEW

**Comment by Tbaut** [comment]
It didn't do the trick unfortunately.

**Comment by amaurymartiny** [comment]
^ Attempt #2: Use .ico file.

**Comment by Tbaut** [comment]
:D `/fether/packages/fether-electron/static/assets/logo/logo.ico must be at least 256x256`

**Comment by axelchalon** [comment]
icon shows up fine here (tried with snapcraft with commit `b85434e`, i.e. 512x512 png)

**Comment by Tbaut** [comment]
I tried with the binary and it shows this image

**Comment by amaurymartiny** [comment]
@Tbaut hmm you're trying with the binary from the draft version right? I remember renaming Fether to Parity Fether (https://github.com/paritytech/fether/blob/master/packages/fether-electron/electron-builder.json#L12)

**Comment by Tbaut** [comment]
I get the binary locally from `./packages/fether-electron/dist/fether-0.1.0/fether` after doing a `yarn package` on the branch ([gist](https://gist.github.com/Tbaut/4975aa8483c8f07aca642968bf347181))

**Comment by amaurymartiny** [comment]
I'm in favor of merging this, it can only be better than the 1024 one. Comments?

**Comment by axelchalon** [comment]
:+1:

**Pull request merged**
