### PR TITLE
feat: Relates to #425. Launch on Startup preference context menu item

### PR DESCRIPTION
**Pull request by ltfschoen**
* [x] - Works on macOS
* [x] - Works on Linux
  * Note: Verify that it works by checking that the checkbox value shown in the context menu matches whether or not there is an entry in the Linux Mint menu "Preferences > Startup Applications" 
* [ ] - Works on Windows - Unable to test on Windows until resolved issue https://github.com/paritytech/fether/issues/446, since I can only use it with a VM

### CODE REVIEW

**Comment by Tbaut** [comment]
Oh I hadn't seen you need help on that one to test. If you can resolve the conflicts I'm happy to help.

**Comment by ltfschoen** [comment]
@Tbaut I've fixed merge conflicts, need help testing it

**Comment by ltfschoen** [comment]
We use electron-settings library to store whether to launch on startup or not. These settings are stored in  ~/USERNAME/.config/Electron/Settings on Linux for example. We need to check to ensure that when we set "launch on startup" to true for a specific user account, that it doesn't change the configuration of any other user accounts.

**Comment by Tbaut** [comment]
I finally took some time to test on windows but unfortunately I can't see this "Preference>Launch on startup" menu.

Note that I introduced mistakes when merging `master` into this branch but it should now be fixed. Fether is working as expected, I could build the package without problem. I havn't tested on linux yet.

**Comment by Tbaut** [comment]
closing as stale

**Pull request closed without merging**
