### PR TITLE
fix: Fixes #298 and #299. Validate input amount of 15 significant digits or more

### LINKED ISSUE #298: Uncaught Error: [format/input::inNumber16] the given number is not an integer
When I go to the "Send Ether" page, with balance of 0.998957 ETH, then enter recipient (i.e. 0x005072Fb985cc64d8A1Ce00ECe26279f73c12F8a), then paste an amount of 0.0000630000000000001, it will crash with an error in the Developer Tools Console:
```
input.js:122 Uncaught Error: [format/input::inNumber16] the given number is not an integer: 63,000,000,000,001.1
```

Relates to https://github.com/paritytech/fether/issues/247

Edit: Note that it also generates an error: 
```
index.js:2178 TypeError: Cannot read property 'mul' of null
    at TxForm.js:211
    at flush (index.js:62)
```

### PR DESCRIPTION
**Pull request by ltfschoen**
The `validateForm` function runs the `preValidate` function, which validates the input fields when a user tries to transfer tokens. 
Previously if users entered a valid recipient address and it passed the existing validation checks it would call the `gas` property function of the decorator's `updates` method to estimate the gas, which doesn't support values of 15 significant digits or more and was causing errors (i.e. large amount of 111111111111111 that has 15 significant digits or more, or for example a small amount of 0.000100000000000001 that also has 15 significant digits). It would be unlikely that a user would transfer more than 100000000 ETH since that's the total supply, but other tokens may have larger total supply.

These changes prevent the the gas estimation from occurring until the user enters a value having less than 15 significant digits.

Suggest merging https://github.com/paritytech/fether/pull/296/files first, and then updating this.

### CODE REVIEW

**Comment by ltfschoen** [comment]
i've added a couple of extra commits to clean it up

**Comment by amaurymartiny** [comment]
@ltfschoen I merged your previous PR, could you fix the conflicts in this one?

**Comment by ltfschoen** [comment]
@amaurymartiny yes, i've fixed the conflicts

**Comment by ltfschoen** [comment]
i'll look at this once this PR is done https://github.com/paritytech/fether/pull/274

**Comment by ltfschoen** [comment]
Closing as #298 and #299 have been resolved, but this error that has emerged remains: https://github.com/paritytech/fether/issues/322

**Pull request closed without merging**
