### PR TITLE
Bump version to 0.2.0

### PR DESCRIPTION
**Pull request by Tbaut**
My linter removed empty lines at the end of files. Let me know if that's a problem.

### CODE REVIEW

**Comment by amaurymartiny** [comment]
Hey Thibaut, I'm pretty sure I told you the contrary before (I was mistaken), but the version in `lerna.json` actually also needs to match up 0.2.0

**Comment by Tbaut** [comment]
Ack, I bumped lerna.json I'll prepare the PR to bump to 0.3.

**Comment by amaurymartiny** [comment]
Hmm, I maybe wasn't clear. What I meant is that we keep 0.2.0 until we release beta. Only after the release do we do 0.3.0.

**Comment by Tbaut** [comment]
Ok that's also fine.

**Pull request merged**
